### ISSUE TITLE
Model definition is out of date.

### ISSUE THREAD

**Issue by CptSpaceToaster** [PokemonTCG/pokemon-tcg-sdk-typescript#2]
The API exposes `subType: ISubType` and `superType: ISuperType ` and they don't align with responses from the API.

1. Why did the name's case change? `console.log(card);` yields that `subtype` and `supertype` are the fields I want, but the type defined in this API says they're supposed to be `subType` and `superType`
```
{…}
  ability: Object
  artist: "TOKIYA"
  attacks: Array(1)
  convertedRetreatCost: 2
  hp: "120"
  id: "xy10-78"
  imageUrl: "https://images.pokemontcg.io/xy10/78.png"
  imageUrlHiRes: "https://images.pokemontcg.io/xy10/78_hires.png"
  name: "Lugia"
  nationalPokedexNumber: 249
  number: "78"
  rarity: "Rare"
  resistances: Array(1)
  retreatCost: Array(2)
  series: "XY"
  set: "Fates Collide"
  setCode: "xy10"
  subtype: "Basic"
  supertype: "Pokémon"
  types: Array(1)
  weaknesses: Array(1)
```

2. Is there a way to digest the card response object to have superType filled instead of undefined?
```
    console.log(this.card.supertype);  // Pokémon
    console.log(this.card.superType);  // undefined
```

**Comment by glinesbdev** [comment]
Thanks for pointing out the differences in the property names. I'll update that to make it more uniform withe the other properties.

As far as the second question, it is "normal" in JavaScript (TypeScript) to have `undefined` as something that isn't there. I could also make this `null`. To make it more consistent with what it return, a string value, I'll opt in to send back an empty string instead. I'm open to any feedback as to what it should return instead of an empty string if you think there is a better way.

**Comment by CptSpaceToaster** [comment]
I took a look, and it just looks like the API has changed datashape _significantly_. I just forked, and was going to submit a PR with all of the fixes, but I'm having some trouble getting a master list of the current Schema.

Things I've found since I last wrote this message:
1. `subType` renamed to `subtype`
2. `subtype` is now just a `string`
3. `superType` renamed to `supertype`
4. `supertype` is now just a `string`
5. `weaknesses` is now an `Interface { type: string; value: string; }`
6. `imageUrlHighRes` renamed to `imageUrlHiRes`

the list goes on

**Comment by glinesbdev** [comment]
There are more issues than I realized. I don't have that much time right now to look over things but I will check out your PR and see what else may need updating after that later today.

**Comment by CptSpaceToaster** [comment]
Updated PR. We're clear for takeoff 👍

**Comment by glinesbdev** [comment]
PR was merged. Closing issue.
